name = "visevo-landing"
compatibility_date = "2025-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "visevo-waitlist"
database_id = "312bb163-e699-45f1-afe4-bc1294ddbe62"
